apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spottle-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
#    kubernetes.io/ingress.class: ambassador
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ $.Values.edge.name }}"
            port:
              number: 80
