engine:
  name: spottle-engine

edge:
  name: spottle-edge

kafka:
  bootstrapServer: kafka.kafka.svc.cluster.local:9092
  topic:
    spottleCommands: spottle.commands.v1
    spottleEvents: spottle.events.v1
